### ISSUE TITLE
Kills are not updated!

### ISSUE THREAD

**Issue by BlushTTV** [MichaelCoding25/KD_Display#1]
Kills are not updated when you do a kills, deaths are updated

**Comment by MichaelCoding25** [comment]
Yeah I'm aware, the resource does not work correctly and I am currently not supporting it, but feel free to put in pull requests.

I might continue to work on it in a few weeks but no promises

**Comment by MichaelCoding25** [comment]
(It is version 0.0.1 after all lol)
